"use client";

import { usePrivy } from "@privy-io/react-auth";
import {
    Box,
    Card,
    CardContent,
    Typography,
    Alert,
    CircularProgress,
    Stack,
    Avatar,
    Grid,
    Chip,
    Divider,
} from "@mui/material";
import { TrendingUp, AccountBalance, CheckCircle, Cancel, Wallet as WalletIcon } from "@mui/icons-material";
import { PublicKey } from "@solana/web3.js";

import { FullScreenLoader } from "@/components/ui/fullscreen-loader";
import { LoginPrompt } from "@/components/auth/LoginPrompt";
import { useBackendUserStore } from "@/lib/stores/backendUserStore";
import { useWalletTokenBalances } from "@/hooks/useWalletTokenBalances";
import {
    formatSocialScore,
    formatTokenBalance,
    getTokenName,
} from "@/lib/utils/formatting";

// Token mint addresses - these should match your deployed tokens
// For localnet, these are generated by the bootstrap script
// You can update these or fetch them from the config PDA
const BLING_MINT = process.env.NEXT_PUBLIC_BLING_MINT || "";
const USDC_MINT = process.env.NEXT_PUBLIC_USDC_MINT || "";
const STABLECOIN_MINT = process.env.NEXT_PUBLIC_STABLECOIN_MINT || "";

function ProfileContent() {
    const { ready, authenticated } = usePrivy();
    const { user: backendUser, isLoading, error } = useBackendUserStore();


    // Get wallet token balances
    const mintAddresses = [BLING_MINT, USDC_MINT, STABLECOIN_MINT].filter(Boolean);
    const { balances, loading: loadingBalances } = useWalletTokenBalances(
        mintAddresses,
        USDC_MINT,
        STABLECOIN_MINT
    );

    if (!ready) {
        return <FullScreenLoader />;
    }

    if (!authenticated) {
        return <LoginPrompt />;
    }

    // Get BLING decimals from wallet balances (defaults to 9 if not available)
    const blingDecimals = balances[BLING_MINT]?.decimals ?? 9;

    return (
        <Box sx={{ p: 3, maxWidth: 1200, mx: "auto" }}>
            {isLoading && (
                <Box sx={{ display: "flex", justifyContent: "center", p: 4 }}>
                    <CircularProgress />
                </Box>
            )}

            {error && (
                <Alert severity="error" sx={{ mb: 2 }}>
                    Error: {error}
                </Alert>
            )}

            {backendUser && (
                <Box sx={{ display: "flex", flexWrap: "wrap", gap: 3 }}>
                    {/* Profile Header */}
                    <Box sx={{ width: { xs: "100%", md: "calc(50% - 12px)" } }}>
                        <Card>
                            <CardContent>
                                <Stack spacing={3}>
                                    <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
                                        <Avatar
                                            src={backendUser.profile?.avatarUrl || undefined}
                                            sx={{
                                                width: 100,
                                                height: 100,
                                                bgcolor: "primary.main",
                                                fontSize: "2.5rem",
                                            }}
                                        >
                                            {backendUser.profile?.displayName
                                                ?.charAt(0)
                                                .toUpperCase() || "U"}
                                        </Avatar>
                                        <Box sx={{ flex: 1 }}>
                                            <Typography variant="h4" sx={{ fontWeight: 700, mb: 0.5 }}>
                                                {backendUser.profile?.displayName || "User"}
                                            </Typography>
                                            <Typography variant="body1" color="text.secondary" sx={{ mb: 1 }}>
                                                @{backendUser.profile?.handle || "unknown"}
                                            </Typography>
                                            {backendUser.profile?.bio && (
                                                <Typography variant="body2" color="text.secondary">
                                                    {backendUser.profile.bio}
                                                </Typography>
                                            )}
                                        </Box>
                                    </Box>
                                </Stack>
                            </CardContent>
                        </Card>
                    </Box>

                    {/* On-Chain Stats */}
                    <Box sx={{ width: { xs: "100%", md: "calc(50% - 12px)" } }}>
                        <Card>
                            <CardContent>
                                <Typography variant="h6" gutterBottom sx={{ mb: 2, display: "flex", alignItems: "center", gap: 1 }}>
                                    <TrendingUp sx={{ fontSize: 20 }} />
                                    On-Chain Stats
                                </Typography>
                                <Stack spacing={2}>
                                    <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                        <Typography variant="body2" color="text.secondary">
                                            Account Status:
                                        </Typography>
                                        {backendUser.hasOnchainAccount ? (
                                            <Chip
                                                icon={<CheckCircle />}
                                                label="Active"
                                                color="success"
                                                size="small"
                                            />
                                        ) : (
                                            <Chip
                                                icon={<Cancel />}
                                                label="Not Created"
                                                color="default"
                                                size="small"
                                            />
                                        )}
                                    </Box>

                                    <Divider />

                                    <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                        <Typography variant="body2" color="text.secondary">
                                            Social Score:
                                        </Typography>
                                        <Typography variant="h6" sx={{ fontWeight: 600 }}>
                                            {formatSocialScore(backendUser.socialScore)}
                                        </Typography>
                                    </Box>

                                    <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                        <Typography variant="body2" color="text.secondary">
                                            Vault Balance:
                                        </Typography>
                                        <Typography variant="h6" sx={{ fontWeight: 600 }}>
                                            {formatTokenBalance(backendUser.vaultBalance, blingDecimals)} BLING
                                        </Typography>
                                    </Box>
                                </Stack>
                            </CardContent>
                        </Card>
                    </Box>

                    {/* Wallet Info */}
                    <Box sx={{ width: { xs: "100%", md: "calc(50% - 12px)" } }}>
                        <Card>
                            <CardContent>
                                <Typography variant="h6" gutterBottom sx={{ mb: 2, display: "flex", alignItems: "center", gap: 1 }}>
                                    <AccountBalance sx={{ fontSize: 20 }} />
                                    Wallet
                                </Typography>
                                <Stack spacing={2}>
                                    <Box>
                                        <Typography variant="body2" color="text.secondary" gutterBottom>
                                            Address:
                                        </Typography>
                                        <Typography
                                            variant="body2"
                                            sx={{
                                                fontFamily: "monospace",
                                                wordBreak: "break-all",
                                                bgcolor: "grey.100",
                                                p: 1,
                                                borderRadius: 1,
                                            }}
                                        >
                                            {backendUser.wallet}
                                        </Typography>
                                    </Box>
                                </Stack>
                            </CardContent>
                        </Card>
                    </Box>

                    {/* Wallet Token Balances */}
                    <Box sx={{ width: { xs: "100%", md: "calc(50% - 12px)" } }}>
                        <Card>
                            <CardContent>
                                <Typography variant="h6" gutterBottom sx={{ mb: 2, display: "flex", alignItems: "center", gap: 1 }}>
                                    <WalletIcon sx={{ fontSize: 20 }} />
                                    Wallet Token Balances
                                </Typography>
                                {loadingBalances ? (
                                    <Box sx={{ display: "flex", justifyContent: "center", p: 2 }}>
                                        <CircularProgress size={24} />
                                    </Box>
                                ) : (
                                    <Stack spacing={2}>
                                        {mintAddresses.map((mint) => {
                                            const balance = balances[mint];
                                            const tokenName = getTokenName(
                                                mint,
                                                BLING_MINT,
                                                USDC_MINT,
                                                STABLECOIN_MINT
                                            );

                                            if (!balance) return null;

                                            return (
                                                <Box key={mint}>
                                                    <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                                                        <Typography variant="body2" color="text.secondary">
                                                            {tokenName}:
                                                        </Typography>
                                                        <Typography variant="h6" sx={{ fontWeight: 600 }}>
                                                            {balance.loading ? (
                                                                <CircularProgress size={16} />
                                                            ) : balance.error ? (
                                                                <Typography variant="body2" color="error">
                                                                    Error
                                                                </Typography>
                                                            ) : (
                                                                formatTokenBalance(balance.balance, balance.decimals)
                                                            )}
                                                        </Typography>
                                                    </Box>
                                                    {balance.error && (
                                                        <Typography variant="caption" color="error" sx={{ mt: 0.5, display: "block" }}>
                                                            {balance.error}
                                                        </Typography>
                                                    )}
                                                    {mintAddresses.indexOf(mint) < mintAddresses.length - 1 && <Divider sx={{ mt: 1 }} />}
                                                </Box>
                                            );
                                        })}
                                        {mintAddresses.length === 0 && (
                                            <Alert severity="info" sx={{ mt: 1 }}>
                                                No token mints configured. Please set NEXT_PUBLIC_USDC_MINT and NEXT_PUBLIC_STABLECOIN_MINT environment variables to view balances.
                                            </Alert>
                                        )}
                                    </Stack>
                                )}
                            </CardContent>
                        </Card>
                    </Box>
                </Box>
            )
            }

            {
                !backendUser && !isLoading && (
                    <Alert severity="info">
                        No profile data available. Please complete onboarding.
                    </Alert>
                )
            }
        </Box >
    );
}

export default function Profile() {
    return <ProfileContent />;
}

