import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/providers/providers";
import { AuthenticatedLayout } from "@/components/layout/AuthenticatedLayout";

const inter = localFont({
  src: "../../public/fonts/InterVariable.ttf",
  variable: "--font-inter",
  display: "swap",
});

const abcFavorit = localFont({
  src: "../../public/fonts/ABCFavorit-Medium.woff2",
  variable: "--font-abc-favorit",
  display: "swap",
});

const goetsusiojiFont = localFont({
  src: "../../public/fonts/goetsusioji.ttf",
  variable: "--font-goetsusioji",
  display: "swap",
});

const jyutcitziFont = localFont({
  src: "../../public/fonts/JyutcitziWithPMingLiURegular.ttf",
  variable: "--font-jyutcitzi",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Privy Next demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${abcFavorit.variable} ${goetsusiojiFont.variable} ${jyutcitziFont.variable} antialiased`}
      >
        <Providers>
          <AuthenticatedLayout>{children}</AuthenticatedLayout>
        </Providers>
      </body>
    </html>
  );
}
